Circe Encoder/Decoder derivation
theiterators/kebs pull request #83
Opened 2020-12-01 21:08 UTC by pk044

2020-12-03 14:59 UTC, asoltysik commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
Maybe we should export this function instead of the specific ones below?

2020-12-03 15:05 UTC, asoltysik commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
Also, maybe it's worth to separately provide `Decoder` and `Encoder` instances? Its probably quite rare that someone needs only one, but I once had a case where I only needed `Decoder` and defining the `Encoder` but be quite difficult.

2020-12-03 15:12 UTC, asoltysik commented on circe/src/main/scala/pl/iterators/kebs/circe/KebsEnumFormats.scala
> +  def lowercaseEnumDecoder[E <: EnumEntry](enum: Enum[E]): Decoder[E] =
I think this should be decided by the end user in the enum definition, not by us. https://github.com/lloydmeta/enumeratum#mixins-to-override-the-name

WDYT?

2020-12-03 15:26 UTC, asoltysik requested changes

2020-12-03 15:26 UTC, asoltysik commented on circe/src/main/scala/pl/iterators/kebs/circe/noflat.scala
> +final class noflat extends scala.annotation.StaticAnnotation
Could you describe how does this work and why is it an annotation? Preferably also in the README because this is undocumented

2020-12-03 15:53 UTC, pk044 commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
https://github.com/circe/circe/blob/master/modules/shapes/src/main/scala/io/circe/shapes/TaggedInstances.scala 

this is basically a copy-paste to make Circe work with Kebs tagged types. i'm not sure why should we provide separate Decoder and Encoder instances - instead we are providing a `Codec` instances which contain both of them. can you elaborate on that? is there any specific use-case you have in mind?

2020-12-03 15:55 UTC, pk044 commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
'export' as in, expose it to the user? or do you just want to provide a `Codec[U @@ T]` instance for any primitive type in one method, instead of creating separate method for each primitive type (just like right it's implemented right now)?

2020-12-03 16:00 UTC, pk044 commented on circe/src/main/scala/pl/iterators/kebs/circe/KebsEnumFormats.scala
> +  def lowercaseEnumDecoder[E <: EnumEntry](enum: Enum[E]): Decoder[E] =
hmm, it's done similarly as in our spray-json implementation - if it's possible, we should refactor it everywhere else too. I guess we can do some research on this :)

2020-12-03 16:03 UTC, pk044 commented on circe/src/main/scala/pl/iterators/kebs/circe/noflat.scala
> +final class noflat extends scala.annotation.StaticAnnotation
it is indeed undocumented in our Circe section - but you can see how it works in our spray-json section in the documentation.

Since it's a common concept, we could make a separate section describing how NoFlat works in all implementations.

2020-12-04 11:58 UTC, asoltysik commented on circe/src/main/scala/pl/iterators/kebs/circe/noflat.scala
> +final class noflat extends scala.annotation.StaticAnnotation
> Since it's a common concept, we could make a separate section describing how NoFlat works in all implementations.
That probably would be best :+1:

2020-12-04 11:58 UTC, asoltysik commented on circe/src/main/scala/pl/iterators/kebs/circe/KebsEnumFormats.scala
> +  def lowercaseEnumDecoder[E <: EnumEntry](enum: Enum[E]): Decoder[E] =
If that's already in the library I guess it should be a part of another PR.

2020-12-04 12:06 UTC, asoltysik commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
Yeah, for example this one: https://stackoverflow.com/a/60005696/3645391

The answer provides an implementation of `Encoder`, but its not actually needed at all in this use-case (PATCH requests) and also its kind of a hack, so I would prefer to define the `Decoder` only. I know tagging such a structure is a quite far-fetched use case, so I'm not blocking the PR on that.

2020-12-04 12:08 UTC, asoltysik commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
Yeah, both. Leave only 
```
implicit def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T]
```

And delete all instances for primitives. Would that work?

2020-12-04 12:28 UTC, pk044 commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
well, not quite. the reason why we need those Codecs defined is because Kebs won't be able to generate Encoders/Decoders for case classes containing tagged types - so the user has to mix-in this trait just to make kebs-cire work with tagged types.

2020-12-04 12:31 UTC, pk044 commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
I see, but I think the issue you linked is a totally different use-case - this trait solely exists to provide those primitive type encoder/decoder instances for Kebs, not the user :P

2020-12-04 12:32 UTC, asoltysik commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
Oh, that I didn't know :+1:

2020-12-04 12:34 UTC, asoltysik approved these changes

2020-12-04 17:23 UTC, pk044 commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
those instances were added 6 months ago to Circe, but they are using `shapeless.@@` https://github.com/circe/circe/pull/1480/files

I added and tweaked them here to use kebs-tagged instead. Circe needs those Codecs to derive encoders/decoders for tagged types - but if I'm wrong - I'm always open to getting rid of this code :P

2020-12-04 17:26 UTC, luksow commented on tagged/src/main/scala/pl/iterators/kebs/tagged/circe/CirceSupport.scala
> +  private def taggedCodec[U: Decoder: Encoder, T]: Codec[U @@ T] =
Hmm, it might be that we're mising that for spray-json too. In that case, we need to add it to the both but as a seperate task. If they exist for spray-json, we need them. However, in any case, I think it can be generalized, so that "if a encoder/decoder exists for X, it exists for X @@ Y".

2020-12-09 17:23 UTC, dbronecki commented on tagged-meta/src/test/scala/CirceAnnotationTests.scala
> +class CirceAnnotationTests extends FunSuite with Matchers with KebsCirce {
It doesn't compile:
```
object FunSuite is not a member of package org.scalatest
```

2020-12-09 17:33 UTC, dbronecki commented on circe/src/test/scala/CirceFormatTests.scala
> +  test("Format - case class with > 22 fields") {
I suggest to add another test case - two nested case classes with > 22 fields (see https://github.com/theiterators/kebs/blob/master/spray-json/src/test/scala/SprayJsonFormatTests.scala#L244) - there was a problem with spray-json and kebs in cases like that, so I think it's beneficial to add such test case to be sure that it works correctly.

2020-12-09 17:51 UTC, dbronecki commented on circe/src/main/scala/pl/iterators/kebs/circe/KebsCirceMacros.scala
> +  }
It's exact copy of SnakifyVariant object in spray-json module - it would be good idea to extract it somewhere to avoid code repetition

2020-12-09 17:54 UTC, dbronecki commented on circe/src/main/scala/pl/iterators/kebs/circe/noflat.scala
> +final class noflat extends scala.annotation.StaticAnnotation
If you call `@noflat` common concept somewhere in docs, please remember that it doesn't exists in play-json - it might be worth mentioning.

2020-12-09 18:00 UTC, dbronecki commented on build.sbt
> +val circe           = "io.circe" %% "circe-core" % "0.14.0-M1"
Is it good idea to depend on unstable version of circe? Maybe it's better to use `0.13.0`?

2020-12-10 09:04 UTC, pk044 commented on build.sbt
> +val circe           = "io.circe" %% "circe-core" % "0.14.0-M1"
it is not :wink: I was experimenting with circe-shapes (which was introduced in milestone release) - but it seems like it won't be needed anymore. Will revert it to 0.13.0.

2020-12-11 16:15 UTC, dbronecki commented on build.sbt
> +  libraryDependencies += circeParser
```suggestion
  libraryDependencies += circeParser % "test"
```
circe-parser module is used only in test, so we can add it as test only dependency

2020-12-23 15:03 UTC, pk044 commented on circe/src/main/scala/pl/iterators/kebs/circe/KebsCirceMacros.scala
> +  }
do you think that the macroUtils module would be a good place for `SnakifyVariant`?

2020-12-23 15:03 UTC, pk044 commented on circe/src/test/scala/CirceFormatTests.scala
> +  test("Format - case class with > 22 fields") {
done!

2021-01-05 13:47 UTC, dbronecki approved these changes

2021-01-11 15:38 UTC, merged